title = "きらきら星変奏曲のテーマより冒頭部分を抜粋"

[model]
smf = "model.mid"
list = "model.list.txt"

[text]
missing = "" # 空文字列はバツ印
extra = "余計" # 空文字列は文字なし
far_behind = "遅れすぎ"
far_ahead = "早すぎ"
too_long = "長すぎ"
too_short = "短すぎ"
tempo_too_fast = "テンポ速すぎ"
tempo_too_slow = "テンポ遅すぎ"
perfect = "すばらしい！"
